package:
  name: depdigest
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: '{{ environ.get(''DEPDIGEST_CONDA_BUILD_NUMBER'', ''0'') }}'
  noarch: python
requirements:
  build:
  - python >=3.11,<3.14
  - pip
  - setuptools >=61.0
  - versioningit >=3.0
  run:
  - python >=3.11,<3.14
  - smonitor >=0.13.0
test:
  imports:
  - depdigest
  commands:
  - python -c "import importlib.metadata as md, os, depdigest; expected=os.environ['PKG_VERSION'];
    assert md.version('depdigest') == expected; assert depdigest.__version__ == expected"
  - depdigest --help
about:
  home: https://www.uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library provides some useful methods to work with quantities

    '
  dev_url: https://www.github.com/uibcdf/depdigest
  doc_url: https://www.uibcdf.org/depdigest
